// setup-env.ts — generate the Docker `.env` automatically.
//
// Saves you from hand-hunting the deep Cowork logs path: it auto-detects the
// `…\Packages\Claude_<hash>\…\local-agent-mode-sessions` root and pulls the gateway creds
// from a ccs profile, then writes a ready-to-use `.env` for docker-compose.
//
//   bun run setup:env            # write .env (won't clobber an existing one)
//   bun run setup:env --force    # overwrite
//   MINER_CCS_PROFILE=son MINER_SOURCE=cowork bun run setup:env

import { existsSync, writeFileSync } from "fs";
import { firstExistingCoworkRoot } from "./src/ingest/cowork.ts";
import { configureRunner, runnerEnv } from "./src/llm/runner.ts";

const force = process.argv.includes("--force");
if (existsSync(".env") && !force) {
  console.error("[setup-env] .env already exists — pass --force to overwrite.");
  process.exit(1);
}

// 1) Gateway creds from the ccs profile (parseExports already handles Windows PowerShell output).
const profile = process.env.MINER_CCS_PROFILE || "son";
configureRunner({ runner: "ccs", ccsProfile: profile });
const env = await runnerEnv();
const base = env.ANTHROPIC_BASE_URL || "";
const token = env.ANTHROPIC_AUTH_TOKEN || "";
if (base && token) console.log(`[setup-env] creds from ccs profile "${profile}" ✓`);
else console.warn(`[setup-env] ⚠ no creds from ccs profile "${profile}" — leaving placeholders (fill ANTHROPIC_* by hand, or check \`ccs env ${profile}\`).`);

// 2) Cowork logs path. Forward-slash it so the docker-compose volume doesn't choke on the
//    Windows drive colon (C:\ → C:/).
const root = firstExistingCoworkRoot();
const coworkLogs = root ? root.replace(/\\/g, "/") : "./logs";
if (root) console.log(`[setup-env] detected Cowork logs: ${coworkLogs}`);
else console.warn("[setup-env] ⚠ no Cowork logs found here — COWORK_LOGS left as ./logs (Code-only box? set it by hand).");

// 3) Write .env.
const lines = [
  "# Auto-generated by `bun run setup:env`. Contains secrets — gitignored.",
  `ANTHROPIC_BASE_URL=${base || "https://your-gateway.example"}`,
  `ANTHROPIC_AUTH_TOKEN=${token || "replace-me"}`,
  `COWORK_LOGS=${coworkLogs}`,
  `MINER_SOURCE=${process.env.MINER_SOURCE || "cowork"}`,
  "MINER_MAX_COST=",
  "",
];
writeFileSync(".env", lines.join("\n"), "utf8");
console.log(`[setup-env] wrote .env${force ? " (overwritten)" : ""}.`);
