// setup-env.ts — generate the Docker `.env` automatically.
//
// Saves you from hand-hunting the deep Cowork logs path: it auto-detects the
// `…\Packages\Claude_<hash>\…\local-agent-mode-sessions` root and pulls the gateway creds
// from a ccs profile, then writes a ready-to-use `.env` for docker-compose.
//
//   bun run setup:env            # write .env (won't clobber an existing one)
//   bun run setup:env --force    # overwrite
//   MINER_CCS_PROFILE=son MINER_SOURCE=cowork bun run setup:env

import { existsSync, writeFileSync, readdirSync } from "fs";
import { homedir } from "os";
import { join } from "path";
import { firstExistingCoworkRoot } from "./src/ingest/cowork.ts";
import { resolveBin, parseExports } from "./src/llm/runner.ts";

const force = process.argv.includes("--force");
if (existsSync(".env") && !force) {
  console.error("[setup-env] .env already exists — pass --force to overwrite.");
  process.exit(1);
}

// Read one ccs profile's env directly (so we can TRY several — runnerEnv() memoizes one).
async function ccsEnv(profile: string): Promise<Record<string, string>> {
  try {
    const p = Bun.spawn([resolveBin("ccs"), "env", profile], { stdout: "pipe", stderr: "pipe" });
    const out = await new Response(p.stdout).text();
    if ((await p.exited) !== 0) return {};
    return parseExports(out); // handles bash `export` AND Windows PowerShell `$env:` forms
  } catch {
    return {};
  }
}

// 1) Gateway creds — AUTO-DETECT the profile instead of assuming "son" (which is one machine's
//    name). Try MINER_CCS_PROFILE first, then every profile that has a ~/.ccs/<name>.settings.json,
//    then a couple of common names; use the first that actually yields ANTHROPIC_* creds.
const candidates: string[] = [];
const forced = process.env.MINER_CCS_PROFILE?.trim();
if (forced) candidates.push(forced);
try {
  for (const f of readdirSync(join(homedir(), ".ccs"))) {
    const m = f.match(/^(.+)\.settings\.json$/i);
    if (m) candidates.push(m[1]);
  }
} catch {
  /* no ~/.ccs on this box */
}
for (const c of ["default", "son", "my-api"]) candidates.push(c);

let base = "", token = "", profile = "";
const tried = new Set<string>();
for (const cand of candidates) {
  if (!cand || tried.has(cand)) continue;
  tried.add(cand);
  const e = await ccsEnv(cand);
  if (e.ANTHROPIC_BASE_URL && (e.ANTHROPIC_AUTH_TOKEN || e.ANTHROPIC_API_KEY)) {
    base = e.ANTHROPIC_BASE_URL;
    token = e.ANTHROPIC_AUTH_TOKEN || e.ANTHROPIC_API_KEY;
    profile = cand;
    break;
  }
}
if (base && token) console.log(`[setup-env] creds from ccs profile "${profile}" ✓  (auto-detected among: ${[...tried].join(", ")})`);
else console.warn(`[setup-env] ⚠ no ccs profile yielded creds (tried: ${[...tried].join(", ") || "none"}) — leaving placeholders. Fill ANTHROPIC_* by hand or set MINER_CCS_PROFILE.`);

// 2) Cowork logs path. Forward-slash it so the docker-compose volume doesn't choke on the
//    Windows drive colon (C:\ → C:/).
const root = firstExistingCoworkRoot();
const coworkLogs = root ? root.replace(/\\/g, "/") : "./logs";
if (root) console.log(`[setup-env] detected Cowork logs: ${coworkLogs}`);
else console.warn("[setup-env] ⚠ no Cowork logs found here — COWORK_LOGS left as ./logs (Code-only box? set it by hand).");

// 3) Write .env.
const lines = [
  "# Auto-generated by `bun run setup:env`. Contains secrets — gitignored.",
  `ANTHROPIC_BASE_URL=${base || "https://your-gateway.example"}`,
  `ANTHROPIC_AUTH_TOKEN=${token || "replace-me"}`,
  `COWORK_LOGS=${coworkLogs}`,
  `MINER_SOURCE=${process.env.MINER_SOURCE || "cowork"}`,
  "MINER_MAX_COST=",
  "",
];
writeFileSync(".env", lines.join("\n"), "utf8");
console.log(`[setup-env] wrote .env${force ? " (overwritten)" : ""}.`);
