// merge.ts — multi-machine convergence step. Merges several per-machine
// `analysis.db` files into ONE combined DB, preserving provenance.
//
// Many employees run the SAME workflow on their own machines; each produces an
// isolated analysis.db. Merging them into one DB makes clusters denser (more
// episodes per task_type → mine/skillgen see real cross-employee patterns).
//
// Usage:
//   bun run src/analysis/merge.ts --out <merged.db> <in1.db> <in2.db> [...]
//
// Design notes:
//   - The output DB is opened via openDb() so the canonical schema exists.
//   - Provenance is added at RUNTIME (ALTER TABLE sessions ADD COLUMN source)
//     so schema.sql stays owned by the parent — we never edit it here.
//   - PKs (session_id/episode_id/turn_id) are globally unique per machine, so a
//     plain INSERT OR IGNORE union is correct AND idempotent (re-merge is a no-op
//     for rows already present). Disjoint inputs → counts add exactly.
//   - task_clusters + skill_drafts are deliberately SKIPPED: they are derived
//     artifacts regenerated by mine/skillgen on the merged DB.
//   - One bad input never aborts the merge — warn and continue.
import { Database } from "bun:sqlite";
import { openDb } from "../db/db.ts";
import { basename } from "node:path";

// Tables copied as a union, in FK-safe order (sessions before its children).
// `source` is injected only for `sessions`; everything else copies verbatim.
const COPY_TABLES = [
  "sessions",
  "turns",
  "episodes",
  "episode_features",
  "episode_evidence",
  "episode_labels",
] as const;

interface Flags {
  out?: string;
  inputs: string[];
}

function parseFlags(argv: string[]): Flags {
  const f: Flags = { inputs: [] };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--out") {
      f.out = argv[++i];
    } else if (a === "-h" || a === "--help") {
      usage();
      process.exit(0);
    } else if (a.startsWith("--")) {
      console.error(`merge: unknown flag ${a}`);
      usage();
      process.exit(2);
    } else {
      f.inputs.push(a);
    }
  }
  return f;
}

function usage(): void {
  console.error(
    "usage: bun run src/analysis/merge.ts --out <merged.db> <in1.db> <in2.db> [...]"
  );
}

// Intersect the schema-declared columns with what actually exists in this input
// DB, so the copy survives minor schema drift across machine versions.
function commonColumns(input: Database, out: Database, table: string): string[] {
  const cols = (db: Database) =>
    new Set(
      (db.query(`PRAGMA table_info(${table})`).all() as { name: string }[]).map(
        (r) => r.name
      )
    );
  const inCols = cols(input);
  const outCols = cols(out);
  // Preserve the output table's column order; only keep columns present in both.
  return (
    out.query(`PRAGMA table_info(${table})`).all() as { name: string }[]
  )
    .map((r) => r.name)
    .filter((c) => inCols.has(c) && outCols.has(c));
}

// Ensure the runtime-only `source` provenance column exists on sessions.
function ensureSourceColumn(out: Database): void {
  const cols = (
    out.query(`PRAGMA table_info(sessions)`).all() as { name: string }[]
  ).map((r) => r.name);
  if (!cols.includes("source")) {
    out.exec(`ALTER TABLE sessions ADD COLUMN source TEXT`);
  }
}

interface InputStat {
  path: string;
  ok: boolean;
  episodes: number;
  error?: string;
}

function copyOne(out: Database, inputPath: string): InputStat {
  const stat: InputStat = { path: inputPath, ok: false, episodes: 0 };
  let input: Database | undefined;
  try {
    input = new Database(inputPath, { readonly: true });
    const src = basename(inputPath);

    for (const table of COPY_TABLES) {
      // Skip tables that don't exist in this input (schema drift / partial DB).
      const exists = input
        .query(
          `SELECT 1 FROM sqlite_master WHERE type='table' AND name=? LIMIT 1`
        )
        .get(table);
      if (!exists) continue;

      const cols = commonColumns(input, out, table);
      if (cols.length === 0) continue;

      const rows = input.query(`SELECT ${cols.join(", ")} FROM ${table}`).all() as Record<
        string,
        unknown
      >[];
      if (rows.length === 0) continue;

      // For sessions, append the provenance `source` column.
      const insertCols = table === "sessions" ? [...cols, "source"] : cols;
      const placeholders = insertCols.map((c) => `$${c}`).join(", ");
      const insert = out.query(
        `INSERT OR IGNORE INTO ${table} (${insertCols.join(", ")}) VALUES (${placeholders})`
      );

      const tx = out.transaction((batch: Record<string, unknown>[]) => {
        for (const row of batch) {
          const params: Record<string, unknown> = {};
          for (const c of cols) params[`$${c}`] = row[c] ?? null;
          if (table === "sessions") params["$source"] = src;
          insert.run(params);
        }
      });
      tx(rows);
    }

    stat.episodes = (
      input.query(`SELECT COUNT(*) AS n FROM episodes`).get() as { n: number }
    ).n;
    stat.ok = true;
  } catch (e) {
    stat.error = (e as Error).message;
  } finally {
    input?.close();
  }
  return stat;
}

function main(): void {
  const flags = parseFlags(process.argv.slice(2));
  if (!flags.out) {
    console.error("merge: --out <merged.db> is required");
    usage();
    process.exit(2);
  }
  if (flags.inputs.length === 0) {
    console.error("merge: at least one input DB is required");
    usage();
    process.exit(2);
  }

  const out = openDb(flags.out); // creates + migrates the canonical schema
  ensureSourceColumn(out);

  const stats: InputStat[] = [];
  for (const inp of flags.inputs) {
    const s = copyOne(out, inp);
    if (!s.ok) {
      console.warn(`merge: ! skipped ${inp} (${s.error})`);
    }
    stats.push(s);
  }

  const totalEpisodes = (
    out.query(`SELECT COUNT(*) AS n FROM episodes`).get() as { n: number }
  ).n;
  const totalSessions = (
    out.query(`SELECT COUNT(*) AS n FROM sessions`).get() as { n: number }
  ).n;
  const totalSources = (
    out.query(`SELECT COUNT(DISTINCT source) AS d FROM sessions`).get() as {
      d: number;
    }
  ).d;

  out.close();

  // ── Summary ─────────────────────────────────────────────────────────────────
  console.log(`merged → ${flags.out}`);
  for (const s of stats) {
    if (s.ok) {
      console.log(`  ${basename(s.path)}: ${s.episodes} episodes`);
    } else {
      console.log(`  ${basename(s.path)}: SKIPPED (${s.error})`);
    }
  }
  console.log(
    `combined: ${totalEpisodes} episodes · ${totalSessions} sessions · ${totalSources} source(s)`
  );
}

main();
